name: Build PDFs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk

      - name: Compile all TEX files
        run: |
          find . -path "*/metadata.json" | while read meta
          do
            project_dir=$(dirname "$meta")

            mkdir -p "$project_dir/pdf"

            find "$project_dir" -maxdepth 1 -name "*.tex" | while read tex
            do
              echo "Compiling $tex"

              latexmk -pdf -interaction=nonstopmode "$tex"

              pdfname=$(basename "$tex" .tex).pdf

              if [ -f "$pdfname" ]; then
                mv "$pdfname" "$project_dir/pdf/"
              fi
            done
          done

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update PDFs"
