name: Build PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk texlive-full

      - name: Compile all tests
        run: |
          find . -name "Test*.tex" | while read file
          do
            echo "Compiling $file"
            latexmk -pdf -interaction=nonstopmode "$file"
          done

      - name: Create PDF folders and copy PDFs
        run: |
          find . -name "Test*.pdf" | while read pdf
          do
            dir=$(dirname "$pdf")
            mkdir -p "$dir/pdf"
            cp "$pdf" "$dir/pdf/"
          done

      - name: Commit PDFs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto update PDFs"
